# Generated by Django 4.0.5 on 2022-07-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customers_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
